[theme]

# Primary accent for interactive elements
primaryColor = '#31304D'

# Background color for the main content area
backgroundColor = '#161A30'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B6BBC4'

# Color used for almost all text
textColor = '#F0ECE5'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"